#------开发环境配置文件------

server:
  port: 8888

spring:
  devtools:
    restart:
      enabled: true #热加载生效
      additional-paths: src/main/java #额外新增的热加载目录
  #     exclude: (热加载排除目录)

  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 8880
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 8880
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update #自动根据实体类的定义创建、更新、验证数据库表结构: create,create-drop,update,validate
    database: mysql
    show-sql: true

  jta:
    atomikos:
      datasource:
        max-pool-size: 20
        borrow-connection-timeout: 60
      connectionfactory:
        max-pool-size: 20
        borrow-connection-timeout: 60
