#------开发环境配置文件------
server:
  port: 8888

spring:
  devtools:
    restart:
      enabled: true #热加载生效
      additional-paths: src/main/java #额外新增的热加载目录
  #     exclude: (热加载排除目录)

#  datasource:
#    primary:
#      jdbc-url: jdbc:mysql://localhost:3306/test?useUnicode=true
#                &characterEncoding=utf-8&useSSL=false
#                &allowPublicKeyRetrieval=true # MySQL 8.0 Public Key Retrieval is not allowed错误的解决方法
#      username: root
#      password: 8880
#      driver-class-name: com.mysql.cj.jdbc.Driver
#    secondary:
#      jdbc-url: jdbc:mysql://localhost:3306/test2?useUnicode=true
#                &characterEncoding=utf-8&useSSL=false
#                &allowPublicKeyRetrieval=true
#      username: root
#      password: 8880
#      driver-class-name: com.mysql.cj.jdbc.Driver

primarydb:
  uniqueResourceName: primary
  xaDataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
  xaProperties:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    user: root
    password: 8880
  exclusiveConnectionMode: true
  minPoolSize: 3
  maxPoolSize: 10
  testQuery: SELECT 1 from dual #由于采用HikiriCP，用于检测数据库连接是否存活。

secondarydb:
  uniqueResourceName: secondary
  xaDataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
  xaProperties:
    url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    user: root
    password: 8880
  exclusiveConnectionMode: true
  minPoolSize: 3
  maxPoolSize: 10
  testQuery: SELECT 1 from dual #由于采用HikiriCP，用于检测数据库连接是否存活。

