#------开发环境配置文件------

server:
  port: 8888

spring:
  devtools:
    restart:
      enabled: true #热加载生效
      additional-paths: src/main/java #额外新增的热加载目录
  #     exclude: (热加载排除目录)

  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 8880
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update #自动根据实体类的定义创建、更新、验证数据库表结构: create,create-drop,update,validate
    database: mysql
    show-sql: true
