server:
  port: 8888

spring:
  devtools:
    restart:
      enabled: true #热加载生效
      additional-paths: src/main/java #额外新增的热加载目录
#     exclude: (热加载排除目录)


  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8